apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: aksloadtest 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: aksloadtest 
    spec:
      containers:
        - name: aksloadtest 
          image: khcommon.azurecr.io/aksloadtest
          ports:
          - containerPort: 8089