apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodedep-techdemo-deployment
  labels:
    app: nodedep-techdemo
spec:
  replicas: 24
  selector:
    matchLabels:
      app: nodedep-techdemo
  template:
    metadata:
      labels:
        app: nodedep-techdemo
    spec:
      containers:
      - name: nodedep-techdemo
        image: _ACR_NAME_.azurecr.io/nodedep-techdemo:_NODEDEP_TECHDEMO_TAG_
        env:
#          - name: CONNECTION_AGENT
#            value: "{ \"keepAlive\" : true, \"maxSockets\" : 5000 }"
          - name: DEPENDENCY_URL_01
#            value: "https://nodedep-dependency-01.westeurope.azurecontainer.io/"
            value: "http://nodedep-dependency-01.westeurope.azurecontainer.io:8080/"
#            value: "http://20.54.129.130:8080/"
          - name: DEPENDENCY_URL_02
#            value: "https://nodedep-dependency-02.westeurope.azurecontainer.io/"
            value: "http://nodedep-dependency-02.westeurope.azurecontainer.io:8080/"
#            value: "http://104.45.71.169:8080/"
          - name: NODE_TLS_REJECT_UNAUTHORIZED
            value: "0"
          - name: DEPENDENCY_TIMEOUT
            value: "2000"
        resources:
          requests:
            cpu: "400m"
#          limits:
#            cpu: "200m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodedep-techdemo-service
  labels:
    app: nodedep-techdemo
spec:
  selector:
    app: nodedep-techdemo
  ports:
  - name: web
    protocol: TCP
    port: 8080
    targetPort: 3000
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nodedep-techdemo-nginx
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: nodedep-techdemo-service
          servicePort: web
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nodedep-techdemo-servicemonitor
  # Change this to the namespace the Prometheus instance is running in
  namespace: monitoring
  labels:
    app: nodedep-techdemo
    release: prometheus
spec:
  selector:
    matchLabels:
     app: nodedep-techdemo # target gitlab service
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: web
    interval: 15s

